sudo: required
services:
      - docker
berfore_install:
      - docker build -t naidu72/docker-react -f Dockerfile.dev .

script:
        - docker run -it naidu72/docker-react rpm run test -- --coverage
        
